modLoader="javafml"
loaderVersion="[30,)"
license="MIT"

[[mods]]
modId="reterraforged"
displayName="ReTerraForged"
<<<<<<< HEAD
version="0.0.5"
=======
version="0.0.6"
>>>>>>> 29239f1f164d19dbfcccaca4a8277d64e784207c
authors="dags,Won-Ton,raccoonman"
credits="dags,Won-Ton,raccoonman,Steveplays28,EdoEquin0x"
logoFile="logo.png"
displayURL="https://github.com/racoonman2/reterraforged/"
issueTrackerURL="https://github.com/racoonman2/reterraforged/issues"
description="A continuation of https://github.com/TerraForged/TerraForged"

[[dependencies.reterraforged]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.reterraforged]]
	modId = "minecraft"
	mandatory = true
	versionRange = "[1.20.1,)"
	ordering = "NONE"
	side = "BOTH"
